---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-core
  namespace: argocd
spec:
  project: core
  source:
    repoURL: 'https://github.com/abradner/athena-gitops.git'
    targetRevision: main
    path: cluster/core
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
