apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-backend
  annotations:
    # This prevents the race condition where ArgoCD tries to apply this 
    # before the Helm chart has finished installing the CRDs
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    onepasswordSDK:
      auth:
        serviceAccountSecretRef:
          name: op-token
          key: token
          namespace: external-secrets
