apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-backend
  annotations:
    # Tell ArgoCD not to panic during the initial dry-run
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    # Tell ArgoCD to wait until the operator (Wave 0) is healthy before applying this
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    onepasswordSDK:
      vault: "Tooling - Athena"
      auth:
        serviceAccountSecretRef:
          name: op-token
          key: token
          namespace: external-secrets
