apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-backend
spec:
  provider:
    onepasswordSDK:
      auth:
        serviceAccountSecretRef:
          name: op-token
          key: token
          namespace: external-secrets
